apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
        - name: pipeline-Container
          image: ayush111122/pipeline
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pipeline-service
spec:
  selector:
    app: pipeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
